### ISSUE TITLE
Type safety loss compared to vanilla ngrx

### ISSUE THREAD

**Issue by eloiqs** [keenondrums/flux-action-class#1]
Consider this example:

```ts
interface State {
  a: string;
  b: boolean
}

const initialState: State = { a: '', b: false }

class SetA extends ActionStandard<string> {}
class SetB extends ActionStandard<boolean> {}

function stateReducer(state =  initialState, action: ActionStandard): State {
  switch (action.type) {
    case SetA.type:
      return { ...state, b: action.payload }; // assigning boolean to string, no errors
    case SetB.type:
      return { ...state, a: action.payload }; // assigning string to boolean, no errors
    default:
      return state;
  }
}
```

To avoid having to cast the action type in every `case`, the recommended approach is to make the action classes types `readonly`, and do something like that:
```ts
const A_TYPE = 'A';
const B_TYPE = 'B';

class SetA extends Action {
  readonly type = A_TYPE;
  payload: string;
}
class SetB extends Action {
  readonly type = B_TYPE;
  payload: boolean;
}

type MyActions = SetA | SetB;

function stateReducer(state =  initialState, action: MyActions): State {
  switch (action.type) {
    case A_TYPE:
      return { ...state, b: action.payload }; // assigning boolean to string, error
    case B_TYPE:
      return { ...state, a: action.payload }; // assigning string to boolean, error
    default:
      return state;
  }
}
```
I have been wondering if this is something that would be possible to abstract into a library similar as yours 😄

**Comment by fxlrnrpt** [comment]
@eloiqs your typings to the first example are a little off. It actually gives your an error. Always :) Unless you help the compiler to figure out the type.

[Playground](http://www.typescriptlang.org/play/#src=%2F%2F%20Allow%20omitting%20params%20typed%20as%20undefined%0D%0A%2F%2F%20https%3A%2F%2Fgithub.com%2FMicrosoft%2FTypeScript%2Fissues%2F12400%0D%0Aexport%20type%20IActionStandardArgs%3CP%2C%20M%3E%20%3D%20P%20extends%20undefined%0D%0A%20%20%3F%20M%20extends%20undefined%0D%0A%20%20%20%20%3F%20%5B%5D%20%2F%2F%20It%20doesn't%20expect%20any%20parameters%20if%20both%2C%20P%20and%20M%2C%20are%20undefined%0D%0A%20%20%20%20%3A%20%5BP%2C%20M%5D%20%2F%2F%20If%20P%20is%20undefined%2C%20but%20M%20is%20not%2C%20we%20still%20have%20to%20pass%20both%0D%0A%20%20%3A%20M%20extends%20undefined%0D%0A%20%20%3F%20%5BP%5D%20%2F%2F%20P%20is%20not%20undefined%2C%20but%20M%20is.%20which%20means%20we%20expect%20only%20P%0D%0A%20%20%3A%20%5BP%2C%20M%5D%20%2F%2F%20Both%2C%20P%20and%20M%2C%20are%20not%20undefined%2C%20which%20means%20we%20expect%20both%0D%0A%0D%0Aexport%20const%20prefix%20%3D%20'flux-action-class%3A'%0D%0A%0D%0Aexport%20abstract%20class%20ActionStandard%3CPayload%20%3D%20undefined%2C%20Meta%20%3D%20undefined%3E%20%7B%0D%0A%20%20protected%20static%20readonly%20_prefix%3A%20string%20%3D%20prefix%0D%0A%20%20public%20static%20get%20type()%20%7B%0D%0A%20%20%20%20return%20%60%24%7Bthis._prefix%7D%24%7Bthis.name%7D%60%0D%0A%20%20%7D%0D%0A%20%20public%20readonly%20type!%3A%20string%0D%0A%20%20public%20readonly%20payload!%3A%20Payload%0D%0A%20%20public%20readonly%20meta!%3A%20Meta%0D%0A%20%20public%20readonly%20error!%3A%20boolean%0D%0A%0D%0A%20%20constructor(...args%3A%20IActionStandardArgs%3CPayload%2C%20Meta%3E)%20%7B%0D%0A%20%20%20%20const%20payload%20%3D%20args%5B0%5D%20as%20Payload%0D%0A%20%20%20%20const%20meta%20%3D%20args%5B1%5D%20as%20Meta%0D%0A%0D%0A%20%20%20%20%2F%2F%20Actions%20must%20be%20plain%20objects%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20error%3A%20payload%20instanceof%20Error%2C%0D%0A%20%20%20%20%20%20meta%2C%0D%0A%20%20%20%20%20%20payload%2C%0D%0A%20%20%20%20%20%20type%3A%20((this.constructor%20as%20any)%20as%20ActionStandard).type%2C%0D%0A%20%20%20%20%7D%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Ainterface%20State%20%7B%0D%0A%20%20a%3A%20string%3B%0D%0A%20%20b%3A%20boolean%0D%0A%7D%0D%0A%0D%0Aconst%20initialState%3A%20State%20%3D%20%7B%20a%3A%20''%2C%20b%3A%20false%20%7D%0D%0A%0D%0Aclass%20SetA%20extends%20ActionStandard%3Cstring%3E%20%7B%7D%0D%0Aclass%20SetB%20extends%20ActionStandard%3Cboolean%3E%20%7B%7D%0D%0A%0D%0Afunction%20stateReducer(state%20%3D%20%20initialState%2C%20action%3A%20SetA%20%7C%20SetB)%3A%20State%20%7B%0D%0A%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20case%20SetA.type%3A%0D%0A%20%20%20%20%20%20return%20%7B%20...state%2C%20a%3A%20action.payload%20%7D%3B%20%2F%2F%20assigning%20boolean%20to%20string%2C%20no%20errors%0D%0A%20%20%20%20case%20SetB.type%3A%0D%0A%20%20%20%20%20%20return%20%7B%20...state%2C%20b%3A%20action.payload%20%7D%3B%20%2F%2F%20assigning%20string%20to%20boolean%2C%20no%20errors%0D%0A%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20return%20state%3B%0D%0A%20%20%7D%0D%0A%7D)

To be honest, I haven't been using `switch-case` from the start. I prefer doing maps and picking a reducer by key (you can take a look at the approach [in this article of mine (Tip 3: Switch away from switch)](https://medium.com/@andreygoncharov/yet-another-guide-to-reduce-boilerplate-in-your-redux-ngrx-app-3794a2dd7bf)). Another alternative which is even easier to read, imho, is to use [ngrx-actions](https://github.com/amcdnl/ngrx-actions).

Let me think if we still can somehow make it work with `switch-case`.

**Comment by fxlrnrpt** [comment]
Added a [note about the issue to README](https://github.com/keenondrums/flux-action-class#usage-in-reducers)
