### ISSUE TITLE
More Code Examples

### ISSUE THREAD

**Issue by MonteKrysto** [keenondrums/flux-action-class#2]
I like your approach but I find the documentation a little short on some details.  Do you think you could provide more examples of actions and reducers in a CRUD scenario?  For example, are you creating more classes based on different action types?  `DataGetSuccess`,`DataUpdate`, `DataFilter`, etc...  If that is the case it would that we would be trading one type of boilerplate for another.

Thank you, and I look forward to reading more.

**Comment by fxlrnrpt** [comment]
@MonteKrysto yeah, currently I do create a new class for each new action. For CRUD or any other asynchronous side-effect it usually means creating three actions:
- `class ActionInit extends ActionStandard {}`
- `class ActionSuccess extends ActionStandard {}`
- `class ActionError extends ActionStandard<Error> {}`

In other words flux-action-class is no silver bullet which helps to avoid boilerplate at all, but IMHO it helps to reduce some which is good enough, especially when your app becomes bigger. As the app grows these few lines of code that flux-action-class helps to save become a significant absolute number.
